### ISSUE TITLE
switch font family and colors

### ISSUE THREAD

**Issue by DannieBGoode** [DannieBGoode/criptomo#21]
Let's switch font family's and color to system fonts one like those used by medium as they are better to read.

more info:
https://blog.prototypr.io/mediums-new-font-is-another-brand-looking-for-differentiation-14793956f969
https://medium.design/system-shock-6b1dc6d6596f
https://medium.com/skyscanner-design/a-native-font-stack-d9d0db72d6e6
https://css-tricks.com/snippets/css/system-font-stack/

**Comment by dcgoodridge** [comment]
What do you mean with "switch to system color"?

**Comment by DannieBGoode** [comment]
it's not system color , its system fonts and meidum's colors.
