### ISSUE TITLE
BTC earnings Calculator

### ISSUE THREAD

**Issue by DannieBGoode** [DannieBGoode/criptomo#31]
I've created a branch called "calculator".

Things missing in this branch:

- [x]  add a spinner when the request is being made (check js/calculator.js comments)
- [ ]  add a datepicker that is nicer and easier to use? This one looks good https://github.com/dbushell/Pikaday
- [x]  format css so that it looks better, also on responsive.
- [x] add CALCULADORA to the navbar (before GLOSARIO)

**Comment by DannieBGoode** [comment]
On responsive the custom input when you select OTRO is misaligned

**Comment by DannieBGoode** [comment]
I've merged this branch, but mobile still needs some adjustments.

**Comment by dcgoodridge** [comment]
Date picker in windows browsers (chrome, firefox, ie) are all different:
**Chrome** shows 3 buttons in the box and has its own picker:
![chrome](https://user-images.githubusercontent.com/6338233/36354779-afd9c0f6-14d9-11e8-8722-d92b51ce4a5e.png)

**InternetExplorer** looks fine, but it has no picker.
![ie](https://user-images.githubusercontent.com/6338233/36354782-bd7416f8-14d9-11e8-86de-f9eb9b584c22.png)

**Firefox** looks nice and has a date picker.
![firefox](https://user-images.githubusercontent.com/6338233/36354785-c1fc76fc-14d9-11e8-9d7a-33d209ab85a1.png)


Other browsers:
Chrome for android: looks good and uses system-style date picker (perfect).
Android 6.0 default browser: looks good and uses system-style date picker (but there are strange color issues in the date-picker elements)

¿iOS/ Safari?

**Comment by dcgoodridge** [comment]
After looking the date-picker issue, i think the best is to leave the browser handle it (best for cross-browser-platform compatibility)

**Comment by dcgoodridge** [comment]
Closed after #36
