### ISSUE TITLE
"Cotizaciones" Section

### ISSUE THREAD

**Issue by DannieBGoode** [DannieBGoode/criptomo#48]
We are already receiving a JSON with a lot of currencies prices (https://api.coinmarketcap.com/v1/ticker/). Let's save this response to memory and have a new section called _Cotizaciones_:

* Order will be established by the ticker
* Icons should be renamed exactly as the ticker response establishes under "symbol" in order  to paint them dynamically.
* We should have a placeholder for new currencies we don't have an icon for yet.
* This could be an entire new section, or it could be somehow merged with the "CRIPTOMONEDAS" section.

At the end we should have something similar to what we see here: https://coinmarketcap.com/ or here https://www.livecoinwatch.com/

**Comment by DannieBGoode** [comment]
blob:https://web.whatsapp.com/8c6a5a9d-e37c-4c0f-9c79-b5ae3d96b480
![image](https://user-images.githubusercontent.com/4180198/36856793-2a19b6e6-1d77-11e8-9456-a8151169e2c6.png)

**Comment by DannieBGoode** [comment]
* Add selector for EUR/USD
* Use websockets http://coincap.io/ instead of coinmarket API
* Use our icons whenever possible controlling 404 errors

**Comment by dcgoodridge** [comment]
Lets close this Issue (Cotizaciones is already up and running), and create 4 new issues with the tasks above, as "New features".
